START TRANSACTION;
INSERT INTO "public"."authors" ("name", "born", "web", "favorite_author_id") VALUES ('Persistence Author', '2021-03-21 08:23:00.000000'::timestamp, 'http://www.example.com', NULL);
SELECT CURRVAL('authors_id_seq');
INSERT INTO "publishers" ("name") VALUES ('Publisher');
SELECT CURRVAL('publishers_publisher_id_seq');
INSERT INTO "books" ("title", "author_id", "translator_id", "next_part", "ean_id", "publisher_id", "published_at", "printed_at", "price", "price_currency", "orig_price_cents", "orig_price_currency") VALUES ('Book XX', 3, NULL, NULL, NULL, 4, '2021-12-31 23:59:59.000000'::timestamp, NULL, NULL, NULL, NULL, NULL);
SELECT CURRVAL('books_id_seq');
INSERT INTO "public"."authors" ("name", "born", "web", "favorite_author_id") VALUES ('Persistence Author 2', '2021-03-21 08:23:00.000000'::timestamp, 'http://www.example.com', NULL);
SELECT CURRVAL('authors_id_seq');
INSERT INTO "books" ("title", "author_id", "translator_id", "next_part", "ean_id", "publisher_id", "published_at", "printed_at", "price", "price_currency", "orig_price_cents", "orig_price_currency") VALUES ('Book YY', 4, NULL, NULL, NULL, 4, '2021-12-31 23:59:59.000000'::timestamp, NULL, NULL, NULL, NULL, NULL);
SELECT CURRVAL('books_id_seq');
COMMIT;
SELECT "authors".* FROM "public"."authors" AS "authors";
SELECT "books".* FROM "books" AS "books" WHERE "books"."author_id" IN (1, 2, 3, 4) ORDER BY "books"."id" DESC;
START TRANSACTION;
UPDATE "books" SET "title" = 'Book 2#' WHERE "id" = 2;
UPDATE "books" SET "title" = 'Book 1#' WHERE "id" = 1;
UPDATE "books" SET "title" = 'Book 4#' WHERE "id" = 4;
UPDATE "books" SET "title" = 'Book 3#' WHERE "id" = 3;
UPDATE "books" SET "title" = 'Book XX#' WHERE "id" = 5;
UPDATE "books" SET "title" = 'Book YY#' WHERE "id" = 6;
